<?php
    /* @var Netopia\Netcard\Block\Qrcode $block */
    $quote = $block->getQuote();
    $qrcodeDta = $block->getQrcodeData();
    if($qrcodeDta->errors->code === "0") {
       ?>
        <div class="" >
            <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
            <h1 class="">
                <span class="" >Please, scan the "Qr Code" with your Mobilpay WALLET</span>
            </h1>
        </div>
        <?php 
        if(isset($qrcodeDta->transaction->id)) {            
            ?>
            <div id="orderId"  data-order=<?php echo $qrcodeDta->order->id ?>>
                <div>
                    <img 
                        src="https://secure.mobilpay.ro/default/index/qr/id/<?=$qrcodeDta->transaction->id;?>/type/4"
                        alt="Qrcode mobilpay WALLET">
                </div>
                <div class="">
                    <p>
                        <span id="orderStatus">xxxx</span>
                    </p>
                </div>
            </div>
            <script> 
            window.onload = (event) => {
              //console.log('page is fully loaded');
              console.log( "Timer Start" );
              setInterval(function () {
                    var xmlhttp = new XMLHttpRequest();
                    let orderId = document.getElementById('orderId').getAttribute('data-order');
                    xmlhttp.onreadystatechange = function() {
                        console.log('oooooo')
                       if (this.readyState == 4 && this.status == 200) {
                            document.getElementById("orderStatus").innerHTML = this.responseText;
                        } 
                    };
                    xmlhttp.open("GET", "http://35.204.43.65/netopia/payment/status?id=" + orderId, true);
                    xmlhttp.send();
                }, 5000);
             };

            </script>
            <?php
        }
    } else {
        echo '<div class="">
                    <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
                    <h1 class="">
                        <span class="" >OOPS, something is wrong!!</span>
                    </h1>
              </div>';
        // foreach ($imgQrcode->errors->details->item as $key => $value) {
        //           echo ('<h2><b>'.$value->message. '</b> : ' .$value->code.'</h2>');
        //       }      
    }



?>
