<?php
    /* @var Netopia\Netcard\Block\Redirect $block */
    $quote = $block->getQuote();
    $formData = $block->getFormData();
    $paymentUrl = ($block->getConfigData('debug') == 1) ? 'http://sandboxsecure.mobilpay.ro' : 'https://secure.mobilpay.ro';
//    echo '<pre>';
//    var_dump($paymentUrl);
//    var_dump($formData);
//    echo '</pre>';
//    die('1');
    if($formData['status']) {
       ?>
        <form method="post" id="mobilpay-form" action="<?php echo $paymentUrl ?>">
            <input type="hidden" name="data" value="<?php echo $formData['data'] ?>"/>
            <input type="hidden" name="env_key" id="env_key" value="<?php echo $formData['form_key'] ?>"/>
            	<button type="submit" class="button">SEND</button>
        </form>
        <?php
    }else {
        echo '<div class="alert alert-danger" role="alert">
                OOPS, something is wrong, you are not able to redirect into Payment page!
              </div>';
    }

?>
