<?php /* @var Netopia\Netcard\Block\Success $block */ ?>
<?php 
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $orderData = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
    $msg = $orderData['status'] == "canceled" ? "Sorry, You order is canceled!" : "You are successfully paid!";
    
?>
<hr>
<div class="page-title-wrapper">
    <img src="https://suport.mobilpay.ro/np-logo-blue.svg" width="134" alt="Netopia Payment>"/>
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?php echo $msg; ?></span>
    </h1>
</div>
<div class="checkout-success">
    <?php 
        if ($orderData['status'] != "canceled") {
            ?>
            <p>Your order number : <strong><?php echo $block->getOrderId();?></strong></p>
            <p>Your total paid ampunt : <strong><?php echo $orderData->getData('base_grand_total');?></strong></p>
            <?php
        }
    ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
